A,aigu,bas
B,aigu,haut,arrondi,bas,arrondi,gauche,aigu,droite,arrondi,gauche
C,arrondi,bas,arrondi,droite,arrondi,haut
D,aigu,haut,arrondi,bas,arrondi,gauche,arrondi,haut
E,arrondi,bas,arrondi,droite,aigu,gauche,arrondi,droite,arrondi,haut
F,droit,bas
G,arrondi,bas,arrondi,droite,arrondi,haut,arrondi,gauche,aigu,droite
H,aigu,haut,arrondi,bas
I,droit,gauche,arrondi,haut
J,droit,haut
K,arrondi,haut,arrondi,droite,arrondi,bas
L,droit,droite
M,arrondi,bas,aigu,haut,arrondi,bas
N,arrondi,bas,arrondi,haut
O,arrondi,droite,arrondi,haut,arrondi,gauche
P,aigu,haut,arrondi,bas,arrondi,gauche
Q,arrondi,droite,arrondi,haut,arrondi,gauche,aigu,droite
R,aigu,haut,arrondi,bas,arrondi,gauche,aigu,droite
S,arrondi,bas,arrondi,droite,arrondi,gauche,arrondi,haut
T,droit,gauche
U,arrondi,haut
V,aigu,haut
W,arrondi,haut,aigu,bas,arrondi,haut
X,aigu,haut,aigu,bas
Y,arrondi,haut,aigu,bas,arrondi,haut,arrondi,gauche
Z,aigu,gauche,aigu,droite
0,arrondi,droite,arrondi,haut,arrondi,gauche,aigu,bas
1,aigu,bas,droit,droite
2,arrondi,bas,arrondi,gauche,aigu,droite
3,arrondi,bas,arrondi,gauche,aigu,droite,arrondi,gauche,arrondi,haut
4,droit,droite,droit,gauche
5,droit,bas,arrondi,bas,arrondi,gauche,arrondi,haut
6,arrondi,droite,arrondi,haut,arrondi,gauche,arrondi,bas
7,aigu,gauche
8,arrondi,bas,arrondi,droite,arrondi,gauche,arrondi,haut,arrondi,droite
9,arrondi,droite,arrondi,haut,aigu,bas